on: workflow_dispatch

jobs:
  version:
    runs-on: ubuntu-latest
    container:
      image: openjdk:21-jdk-oracle
    steps:
      - name: Audit
        run: java -version
  build:
    runs-on: ubuntu-latest
    container:
      image: openjdk:21-jdk-oracle
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Build App
        run: ./gradlew clean build
